#!/bin/sh -e

CONFIGURE_ARGS="--disable-shared --without-simd"

die() {
  echo "$@" 1>&2
  exit 1
}

download_extract() {
  local FN=`echo $2 | sed 's,.*/\([^?]*\)\?.*,\1,'`
  wget -c -O "$FN" "$2" || true
  local CKSUM=`sha256sum "$FN" | cut -d ' ' -f 1`
  test $3 = $CKSUM || die "$1 has the wrong checksum"
  mkdir --parents "src/$1"
  tar -xzf "$FN" --strip-components=1 -C "src/$1"
}

: <<EOF
(
download_extract libtool \
  'http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz' \
  e3bd4d5d3d025a36c21dd6af7ea818a2afcd4dfc1ea5a17b39d7854bcd0c06e3 
cd src/libtool && ./configure $CONFIGURE_ARGS && make
)

export ACLOCAL_PATH="${ACLOCAL_PATH:+$ACLOCAL_PATH:}$(readlink -e src/libtool/m4)"
EOF

(
download_extract libjpeg-turbo \
  'http://iweb.dl.sourceforge.net/project/libjpeg-turbo/1.3.1/libjpeg-turbo-1.3.1.tar.gz' \
  c132907417ddc40ed552fe53d6b91d5fecbb14a356a60ddc7ea50d6be9666fb9
echo ACLOCAL_PATH is $ACLOCAL_PATH
cd src/libjpeg-turbo && ./configure $CONFIGURE_ARGS && make
)

(
download_extract mozjpeg \
  'https://github.com/mozilla/mozjpeg/releases/download/v3.1/mozjpeg-3.1-release-source.tar.gz' \
  deedd88342c5da219f0047d9a290cd58eebe1b7a513564fcd8ebc49670077a1f
cd src/mozjpeg && ./configure $CONFIGURE_ARGS && make
)

